Repository DeveloperAcademy-POSTECH/MacC-Team-FourFour, pull requests merged in 2022-10, with the labels that each got.

#4 [ADD] 사진 촬영 화면 구현
  Samplero/Samplero.xcodeproj/project.pbxproj
  Samplero/Samplero/Global/Resource/Assets.xcassets/Button/Contents.json
  Samplero/Samplero/Global/Resource/Assets.xcassets/Button/cart.imageset/Contents.json
  Samplero/Samplero/Global/Resource/Assets.xcassets/Button/cart.imageset/cart.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/Sample/Contents.json
  Samplero/Samplero/Global/Resource/Assets.xcassets/Sample/sample_history.imageset/Contents.json
  Samplero/Samplero/Global/Resource/Assets.xcassets/Sample/sample_history.imageset/sample_history_button.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/Sample/sample_photo.imageset/Contents.json
  Samplero/Samplero/Global/Resource/Assets.xcassets/Sample/sample_photo.imageset/example_for_simulator.png
  Samplero/Samplero/Info.plist
  Samplero/Samplero/Screen/Camera/CameraViewController.swift
Labels: ❤️ Woogy, 🏞 UI

#12 [FIX] .gitignore content changed
  .gitignore
  Samplero/Samplero/Global/Support/AppDelegate.swift
Labels: 🐞 Bug, 🤖 Cozy

#13 [ADD] github actions - build success, lint warnings (#6)
  .github/workflows/pre-check.yml
Labels: 🤖 Cozy

#9 [ADD] 견적 내역 화면 구현 (내비게이션 바 부분 제외)
  Samplero/Samplero.xcodeproj/project.pbxproj
  Samplero/Samplero/Global/Base/BaseCollectionViewCell.swift
  Samplero/Samplero/Global/Extension/UICollectionView+Extension.swift
  Samplero/Samplero/Global/Resource/Assets.xcassets/Sample/sample_photo_0.imageset/Contents.json
  Samplero/Samplero/Global/Resource/Assets.xcassets/Sample/sample_photo_0.imageset/sample_photo_7.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/Sample/sample_photo_1.imageset/Contents.json
  Samplero/Samplero/Global/Resource/Assets.xcassets/Sample/sample_photo_1.imageset/sample_photo_4.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/Sample/sample_photo_2.imageset/Contents.json
  Samplero/Samplero/Global/Resource/Assets.xcassets/Sample/sample_photo_2.imageset/sample_photo_1.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/Sample/sample_photo_3.imageset/Contents.json
  Samplero/Samplero/Global/Resource/Assets.xcassets/Sample/sample_photo_3.imageset/sample_photo_6.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/Sample/sample_photo_4.imageset/Contents.json
  Samplero/Samplero/Global/Resource/Assets.xcassets/Sample/sample_photo_4.imageset/sample_photo_3.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/Sample/sample_photo_5.imageset/Contents.json
  Samplero/Samplero/Global/Resource/Assets.xcassets/Sample/sample_photo_5.imageset/sample_photo_0.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/Sample/sample_photo_6.imageset/Contents.json
  Samplero/Samplero/Global/Resource/Assets.xcassets/Sample/sample_photo_6.imageset/sample_photo_5.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/Sample/sample_photo_7.imageset/Contents.json
  Samplero/Samplero/Global/Resource/Assets.xcassets/Sample/sample_photo_7.imageset/sample_photo_2.png
  Samplero/Samplero/Model/EstimateHistory.swift
  Samplero/Samplero/Screen/EstimateHistory/EstimateHistoryViewController.swift
  Samplero/Samplero/Screen/EstimateHistory/View/Cell/EstimateHistoryCollectionViewCell.swift
  Samplero/Samplero/Screen/EstimateHistory/ViewModel/EstimateHistoryViewModel.swift
Labels: ❤️ Woogy, 🏞 UI

#8 [ADD] 견적내기 뷰 추가
  Samplero/Samplero.xcodeproj/project.pbxproj
  Samplero/Samplero/Global/Base/BaseViewController.swift
  Samplero/Samplero/Global/Extension/CGSize+Extension.swift
  Samplero/Samplero/Global/Extension/UICollectionView+Extension.swift
  Samplero/Samplero/Global/Literal/ImageLiteral.swift
  Samplero/Samplero/Global/Protocol/ViewModelBindableType.swift
  Samplero/Samplero/Global/Protocol/ViewModelType.swift
  Samplero/Samplero/Global/Resource/Assets.xcassets/CozyBaby.imageset/Contents.json
  Samplero/Samplero/Global/Resource/Assets.xcassets/CozyBaby.imageset/CozyBaby.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/CozyBaby.imageset/CozyBaby@2x.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/CozyBaby.imageset/CozyBaby@3x.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/CozyGray.imageset/Contents.json
  Samplero/Samplero/Global/Resource/Assets.xcassets/CozyGray.imageset/CozyGray.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/CozyGray.imageset/CozyGray@2x.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/CozyGray.imageset/CozyGray@3x.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/SampleRoom.imageset/Contents.json
  Samplero/Samplero/Global/Resource/Assets.xcassets/SampleRoom.imageset/SampleRoom.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/SampleRoom.imageset/SampleRoom@2x.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/SampleRoom.imageset/SampleRoom@3x.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/ShoppingBag.imageset/Contents.json
  Samplero/Samplero/Global/Resource/Assets.xcassets/ShoppingBag.imageset/ShoppingBag.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/ShoppingBag.imageset/ShoppingBag@2x.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/ShoppingBag.imageset/ShoppingBag@3x.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/SoyBrown.imageset/Contents.json
  Samplero/Samplero/Global/Resource/Assets.xcassets/SoyBrown.imageset/SoyBrown.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/SoyBrown.imageset/SoyBrown@2x.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/SoyBrown.imageset/SoyBrown@3x.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/WhiteMarble.imageset/Contents.json
  Samplero/Samplero/Global/Resource/Assets.xcassets/WhiteMarble.imageset/WhiteMarble.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/WhiteMarble.imageset/WhiteMarble@2x.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/WhiteMarble.imageset/WhiteMarble@3x.png
  Samplero/Samplero/Global/Resource/Base.lproj/Main.storyboard
  Samplero/Samplero/Model/MockData.swift
  Samplero/Samplero/Model/Sample.swift
  Samplero/Samplero/Screen/Estimate/EstimateViewController.swift
  Samplero/Samplero/Screen/Estimate/View/CommonStackView.swift
  Samplero/Samplero/Screen/Estimate/View/SampleDetailView.swift
  Samplero/Samplero/Screen/Estimate/View/cell/SampleCollectionViewCell.swift
  Samplero/Samplero/Screen/Estimate/ViewModel/EstimateViewModel.swift
  Samplero/Samplero/Screen/EstimateHistory/EstimateHistoryViewController.swift
  Samplero/Samplero/Screen/Main/MainViewController.swift
Labels: 🌊 Miller, 🏞 UI, Ꜣ Logic, 🧬 Model

#26 [FEAT] 라이브러리에서 사진 가져오기
  Samplero/Samplero/Screen/Camera/CameraViewController.swift
Labels: ❤️ Woogy, Ꜣ Logic

#37 [ADD] UIViewController+Alert Extension 추가
  Samplero/Samplero.xcodeproj/project.pbxproj
  Samplero/Samplero/Global/Extension/UIViewController+Alert.swift
Labels: 🎸 Dani, 🏞 UI

#30 [ADD] SQLite 연결 및 관련 코드 추가
  Samplero/Samplero.xcodeproj/project.pbxproj
  Samplero/Samplero/Global/Service/DBHelper.swift
  Samplero/Samplero/Global/Support/AppDelegate.swift
  Samplero/Samplero/Model/EstimateHistory.swift
  Samplero/Samplero/Model/MockData.swift
  Samplero/Samplero/Model/Sample.swift
  Samplero/Samplero/Screen/EstimateHistory/ViewModel/EstimateHistoryViewModel.swift
Labels: ❤️ Woogy, Ꜣ Logic

#35 [ADD] 약관동의 UI 화면 구현
  Samplero/Samplero.xcodeproj/project.pbxproj
  Samplero/Samplero/Global/Resource/Base.lproj/Main.storyboard
  Samplero/Samplero/Screen/TermsAndConditions/View/CustomCheckbox.swift
  Samplero/Samplero/Screen/TermsAndConditions/View/TermsViewController.swift
Labels: 🎸 Dani, 🏞 UI

#36 [UI] CameraView 화면 전환 연결
  Samplero/Samplero/Screen/Camera/CameraViewController.swift
  Samplero/Samplero/Screen/EstimateHistory/EstimateHistoryViewController.swift
Labels: ❤️ Woogy, 🏞 UI

#48 [ADD] Toast UI 구현
  Samplero/Samplero.xcodeproj/project.pbxproj
  Samplero/Samplero/Global/UIComponent/PaddedLabel.swift
  Samplero/Samplero/Screen/TermsAndConditions/View/TermsViewController.swift
Labels: 🎸 Dani, 🏞 UI

#49 [FEAT] TermsViewModel 을 만들고 체크박스와 카카오 링크 버튼 연결하기
  Samplero/Samplero.xcodeproj/project.pbxproj
  Samplero/Samplero/Screen/TermsAndConditions/View/TermsViewController.swift
  Samplero/Samplero/Screen/TermsAndConditions/ViewModel/TermsViewModel.swift
Labels: 🎸 Dani, Ꜣ Logic

#51 [FEAT] 클립보드 복사 및 카카오 링크 연결 구현
  Samplero/Samplero/Screen/TermsAndConditions/View/TermsViewController.swift
Labels: 🎸 Dani, Ꜣ Logic

#34 [ADD] 장바구니 UI 구현
  Samplero/Samplero.xcodeproj/project.pbxproj
  Samplero/Samplero/Global/Resource/Base.lproj/Main.storyboard
  Samplero/Samplero/Screen/Estimate/View/EstimateCommonStackView.swift
  Samplero/Samplero/Screen/Main/MainViewController.swift
  Samplero/Samplero/Screen/ShopBasket/ShopBasketViewController.swift
  Samplero/Samplero/Screen/ShopBasket/View/Cell/ShopBasketCollectionViewCell.swift
Labels: 🌊 Miller, 🏞 UI

#41 [ADD] 사진 촬영 도움말 뷰 추가
  Samplero/Samplero.xcodeproj/project.pbxproj
  Samplero/Samplero/Global/Resource/Assets.xcassets/couchMarkGuideImage.imageset/Contents.json
  Samplero/Samplero/Global/Resource/Assets.xcassets/couchMarkGuideImage.imageset/couchMarkGuideImage.pdf
  Samplero/Samplero/Screen/Camera/CameraViewController.swift
  Samplero/Samplero/Screen/Camera/View/CameraHelpView.swift
  Samplero/Samplero/Screen/EstimateHistory/EstimateHistoryViewController.swift
Labels: ❤️ Woogy, 🏞 UI

#58 [ADD] UIFont + Extension
  Samplero/Samplero.xcodeproj/project.pbxproj
  Samplero/Samplero/Global/Extension/UIFont+Extension.swift
Labels: 🌊 Miller

#53 [DB] 견적내역사항, 촬영 사진 DB 저장 및 불러오기 구현
  Samplero/Samplero.xcodeproj/project.pbxproj
  Samplero/Samplero/Global/Service/DBHelper.swift
  Samplero/Samplero/Global/Utility/LocalFileManager.swift
  Samplero/Samplero/Model/EstimateHistory.swift
  Samplero/Samplero/Screen/Camera/CameraViewController.swift
  Samplero/Samplero/Screen/EstimateHistory/EstimateHistoryViewController.swift
  Samplero/Samplero/Screen/EstimateHistory/View/Cell/EstimateHistoryCollectionViewCell.swift
  Samplero/Samplero/Screen/EstimateHistory/ViewModel/EstimateHistoryViewModel.swift
  Samplero/Samplero/Screen/TakenPicture/TakenPictureViewController.swift
Labels: ❤️ Woogy, Ꜣ Logic

#54 [ADD] 예상 가격 및 면적 입력 UI 수정, 상황에 맞는 뷰 생성
  Samplero/Samplero.xcodeproj/project.pbxproj
  Samplero/Samplero/Global/UIComponent/PaddedButton.swift
  Samplero/Samplero/Screen/Calculation/AreaTestViewController.swift
  Samplero/Samplero/Screen/Calculation/EstimatedPriceView.swift
  Samplero/Samplero/Screen/Calculation/ToBeEstimatedPriceView.swift
Labels: 🎸 Dani, 🏞 UI

#63 [CHORE] 견적내역뷰 UI 변경
  Samplero/Samplero/Model/MockData.swift
  Samplero/Samplero/Screen/Estimate/EstimateViewController.swift
  Samplero/Samplero/Screen/Estimate/View/EstimateCommonStackView.swift
  Samplero/Samplero/Screen/Estimate/View/SampleDetailView.swift
Labels: 🌊 Miller, 🏞 UI

#65 [FEAT] 면적 입력하면 가격 및 수량 계산
  Samplero/Samplero/Global/Resource/Base.lproj/Main.storyboard
  Samplero/Samplero/Screen/Calculation/AreaTestViewController.swift
  Samplero/Samplero/Screen/Calculation/CustomGetSizeView.swift
  Samplero/Samplero/Screen/Calculation/EstimatedPriceView.swift
  Samplero/Samplero/Screen/Calculation/GetAreaViewController.swift
  Samplero/Samplero/Screen/TermsAndConditions/ViewModel/TermsViewModel.swift
Labels: 🎸 Dani, Ꜣ Logic

#62 [FIX] 견적내역으로 이동하는 버튼의 이미지 설정이 되지 않는 에러 해결
  Samplero/Samplero.xcodeproj/project.pbxproj
  Samplero/Samplero/Screen/Camera/CameraViewController.swift
  Samplero/Samplero/Screen/Camera/ViewModel/CameraViewModel.swift
Labels: 🐞 Bug, ❤️ Woogy

#70 [FEAT] Shopbasketview Choice
  Samplero/Samplero.xcodeproj/project.pbxproj
  Samplero/Samplero/Model/CheckSample.swift
  Samplero/Samplero/Model/Sample.swift
  Samplero/Samplero/Screen/Main/MainViewController.swift
  Samplero/Samplero/Screen/ShopBasket/ShopBasketViewController.swift
  Samplero/Samplero/Screen/ShopBasket/View/AmountFooterView.swift
  Samplero/Samplero/Screen/ShopBasket/View/AmountStackView.swift
  Samplero/Samplero/Screen/ShopBasket/View/Cell/ShopBasketCollectionViewCell.swift
  Samplero/Samplero/Screen/ShopBasket/ViewModel/ShopBasketViewModel.swift
Labels: 🌊 Miller, Ꜣ Logic

#67 [ADD] Icon Assets
  Samplero/Samplero/Global/Resource/Assets.xcassets/AppIcon.appiconset/1024.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/AppIcon.appiconset/114.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/AppIcon.appiconset/120.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/AppIcon.appiconset/180.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/AppIcon.appiconset/29.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/AppIcon.appiconset/40.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/AppIcon.appiconset/57.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/AppIcon.appiconset/58.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/AppIcon.appiconset/60.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/AppIcon.appiconset/80.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/AppIcon.appiconset/87.png
  Samplero/Samplero/Global/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: 🌊 Miller

#75 [FEAT] estimateview getareaview 연결
  Samplero/Samplero/Global/Resource/Base.lproj/Main.storyboard
  Samplero/Samplero/Screen/Calculation/AreaTestViewController.swift
  Samplero/Samplero/Screen/Calculation/EstimatedPriceView.swift
  Samplero/Samplero/Screen/Calculation/GetAreaViewController.swift
  Samplero/Samplero/Screen/Calculation/ToBeEstimatedPriceView.swift
  Samplero/Samplero/Screen/Estimate/EstimateViewController.swift
Labels: 🌊 Miller, 🎸 Dani, Ꜣ Logic

#74 [UI] Shop Basket Terms View 연결
  Samplero/Samplero/.swiftlint.yml
  Samplero/Samplero/Screen/ShopBasket/ShopBasketViewController.swift
  Samplero/Samplero/Screen/ShopBasket/ViewModel/ShopBasketViewModel.swift
  Samplero/Samplero/Screen/TermsAndConditions/View/TermsViewController.swift
Labels: ❤️ Woogy, 🏞 UI, Ꜣ Logic

#77 [UI] Estimate History Cell 테두리 설정
  Samplero/Samplero/Screen/EstimateHistory/View/Cell/EstimateHistoryCollectionViewCell.swift
Labels: ❤️ Woogy, 🏞 UI

#84 [DB] 장바구니 삭제, 수정 코드 추가
  Samplero/Samplero/Global/Service/DBHelper.swift
  Samplero/Samplero/Screen/ShopBasket/ShopBasketViewController.swift
  Samplero/Samplero/Screen/ShopBasket/ViewModel/ShopBasketViewModel.swift
  Samplero/Samplero/Screen/TermsAndConditions/View/TermsViewController.swift
Labels: ❤️ Woogy, Ꜣ Logic

#73 [FEAT] 장 당 가격이 미정인 경우를 처리
  Samplero/Samplero/Screen/Calculation/AreaTestViewController.swift
  Samplero/Samplero/Screen/Calculation/EstimatedPriceView.swift
  Samplero/Samplero/Screen/Calculation/ToBeEstimatedPriceView.swift
Labels: 🎸 Dani, 🏞 UI, Ꜣ Logic

#87 [ADD] 장바구니 뷰에 divider 추가
  Samplero/Samplero/Screen/ShopBasket/ShopBasketViewController.swift
  Samplero/Samplero/Screen/ShopBasket/View/AmountFooterView.swift
Labels: 🎸 Dani, 🏞 UI

#88 [FEAT] 장바구니 샘플 갯수 표시
  Samplero/Samplero/Global/Service/DBHelper.swift
  Samplero/Samplero/Screen/Camera/CameraViewController.swift
  Samplero/Samplero/Screen/Camera/ViewModel/CameraViewModel.swift
  Samplero/Samplero/Screen/Estimate/EstimateViewController.swift
  Samplero/Samplero/Screen/Estimate/ViewModel/EstimateViewModel.swift
Labels: ❤️ Woogy, 🏞 UI

#89 [FEAT] add sample to shopbasket
  Samplero/Samplero/Global/Extension/Color+Extension.swift
  Samplero/Samplero/Global/Service/DBHelper.swift
  Samplero/Samplero/Model/CheckSample.swift
  Samplero/Samplero/Model/Sample.swift
  Samplero/Samplero/Model/ShopBasket.swift
  Samplero/Samplero/Screen/Estimate/EstimateViewController.swift
  Samplero/Samplero/Screen/Estimate/ViewModel/EstimateViewModel.swift
  Samplero/Samplero/Screen/ShopBasket/ShopBasketViewController.swift
  Samplero/Samplero/Screen/ShopBasket/ViewModel/ShopBasketViewModel.swift
Labels: ❤️ Woogy, 🌊 Miller, Ꜣ Logic

#91 [FEAT] 카메라 도움말 뷰 확인 버튼 추가
  Samplero/Samplero/Screen/Camera/CameraViewController.swift
  Samplero/Samplero/Screen/Camera/View/CameraHelpView.swift
  Samplero/Samplero/Screen/EstimateHistory/EstimateHistoryViewController.swift
Labels: ❤️ Woogy, 🏞 UI, 🧬 Model

#96 [FIX] change named loading method
  Samplero/Samplero/Global/Resource/Assets.xcassets/SampleSpread/SpreadBomBomCozyGray.imageset/Contents.json
  Samplero/Samplero/Global/Resource/Assets.xcassets/SampleSpread/SpreadBomBomCozyGray.imageset/SpreadBomBomCozyGrey.jpg
  Samplero/Samplero/Global/Resource/Assets.xcassets/SampleSquare/ThumbnailBomBomCozyGray.imageset/Contents.json
  Samplero/Samplero/Global/Resource/Assets.xcassets/SampleSquare/ThumbnailBomBomCozyGray.imageset/ThumbnailBomBomCozyGrey.jpg
  Samplero/Samplero/Screen/Camera/CameraViewController.swift
  Samplero/Samplero/Screen/Estimate/EstimateViewController.swift
  Samplero/Samplero/Screen/Estimate/ViewModel/EstimateViewModel.swift
Labels: 🐞 Bug, 🤖 Cozy

#98 [FIX] area view error resolved
  Samplero/Samplero.xcodeproj/project.pbxproj
  Samplero/Samplero/Screen/Calculation/EstimatedPriceView.swift
  Samplero/Samplero/Screen/Estimate/EstimateViewController.swift
Labels: 🐞 Bug, 🌊 Miller

#99 Feat/94 lottieview
  Samplero/Samplero.xcodeproj/project.pbxproj
  Samplero/Samplero/Global/Base/BaseViewController.swift
  Samplero/Samplero/Global/Resource/Lottie/dot.json
  Samplero/Samplero/Global/Resource/Lottie/dots.json
  Samplero/Samplero/Screen/Camera/CameraViewController.swift
Labels: 🌊 Miller, 🏞 UI

#97 [FEAT] 장바구니 버튼 연결
  Samplero/Samplero/Global/Service/DBHelper.swift
  Samplero/Samplero/Screen/Camera/CameraViewController.swift
  Samplero/Samplero/Screen/Estimate/EstimateViewController.swift
  Samplero/Samplero/Screen/EstimateHistory/EstimateHistoryViewController.swift
  Samplero/Samplero/Screen/ShopBasket/ShopBasketViewController.swift
  Samplero/Samplero/Screen/ShopBasket/ViewModel/ShopBasketViewModel.swift
Labels: ❤️ Woogy, 🏞 UI, Ꜣ Logic

#102 [ADD] app name localization
  Samplero/Samplero.xcodeproj/project.pbxproj
  Samplero/Samplero/Info.plist
  Samplero/en.lproj/InfoPlist.strings
  Samplero/ko.lproj/InfoPlist.strings
Labels: 🤖 Cozy

#105 [CHORE] add Main.strings, LaunchScreen.strings
  Samplero/Samplero.xcodeproj/project.pbxproj
  Samplero/Samplero/Global/Resource/en.lproj/InfoPlist.strings
  Samplero/Samplero/Global/Resource/ko.lproj/InfoPlist.strings
  Samplero/Samplero/Global/Resource/ko.lproj/LaunchScreen.strings
  Samplero/Samplero/Global/Resource/ko.lproj/Main.strings
Labels: 🤖 Cozy

#104 Feat/103 estimateview refactoring
  Samplero/Samplero.xcodeproj/project.pbxproj
  Samplero/Samplero/Global/Base/BaseViewController.swift
  Samplero/Samplero/Global/Extension/MLMultiArray+Image.swift
  Samplero/Samplero/Global/Extension/RxViewController.swift
  Samplero/Samplero/Global/Extension/UIFont+Extension.swift
  Samplero/Samplero/Global/Extension/UIViewController+Alert.swift
  Samplero/Samplero/Global/Service/DBHelper.swift
  Samplero/Samplero/Screen/Calculation/BottomSheetInteractiveDismissalTransition.swift
  Samplero/Samplero/Screen/Calculation/BottomSheetPresentationController.swift
  Samplero/Samplero/Screen/Calculation/ToBeEstimatedPriceView.swift
  Samplero/Samplero/Screen/Camera/CameraViewController.swift
  Samplero/Samplero/Screen/Estimate/EstimateViewController.swift
  Samplero/Samplero/Screen/Estimate/ViewModel/EstimateViewModel.swift
  Samplero/Samplero/Screen/ShopBasket/ShopBasketViewController.swift
  Samplero/Samplero/Screen/TermsAndConditions/View/TermsViewController.swift
Labels: 🌊 Miller, 🛠 Refactoring

#110 [REFACTOR] shopbasket refactoring
  Samplero/Samplero.xcodeproj/project.pbxproj
  Samplero/Samplero/Screen/ShopBasket/ShopBasketViewController.swift
  Samplero/Samplero/Screen/ShopBasket/View/Cell/ShopBasketCollectionViewCell.swift
  Samplero/Samplero/Screen/ShopBasket/ViewModel/ShopBasketViewModel.swift
Labels: 🌊 Miller, 🛠 Refactoring

#111 [FIX] shopbasket allchoicebutton again
  Samplero/Samplero.xcodeproj/project.pbxproj
  Samplero/Samplero/Screen/ShopBasket/ShopBasketViewController.swift
  Samplero/Samplero/Screen/ShopBasket/ViewModel/ShopBasketViewModel.swift
Labels: 🐞 Bug, 🌊 Miller
